# Site settings
title: Parthaa
logo_image: "/images/logo.png"
description: A space to think deeply, learn openly, and document the journey.
social_media_share_image: "/images/logo.png"
disqus-identifier:
google-analytics: G-XLEGE1T4XZ

# Author Settings
author_name: Swagatika Mohapatra
author_image: "/images/writer.png"

# header
header_menu__settings:
  menu__items:
    - title: "Home"
      url: "/"
    # - title: "Projects"
    #   url: "/projects/"
    - title: "Blog"
      url: "/blog/"
    #    - title: "Pages"
    #      submenu:
    #        - url: "/contact/"
    #          title: "Contact"
    - url: "/about/"
      title: "About"
    # - url: "https://satishw.github.io/jekyll-theme-aura-pro/features"
    #   title: "Aura Pro"

# Footer
footer_menu__settings:
  menu__items:
    - title: "Home"
      url: "/"
    # - title: "Projects"
    #   url: "/projects/"
    - title: "About"
      url: "/about/"
    - title: "Blog"
      url: "/blog/"

# Hero settings
hero__settings:
  title: Hey, I'm Swagatika Mohapatra
  description_html: <strong>A developer, lifelong learner</strong> and <strong>Computer Science educator</strong> who enjoys building things and sharing what I learn. When I'm not coding or teaching, you'll find me reading books, reflecting on ideas, writing about things that interest me, and, of course, battling my mobile addiction 🧐.
  image: /images/me_art.png
  image_alt: Swagatika's picture
  cta_button: Get in touch
  cta_button_link: "/contact"
  # works_button: See my works
  # works_button_link: "#projects"
  works_button: See my blogs
  works_button_link: "#blogs"

projects__settings:
  title: Latest Works
  title_myworks: My Works
  description_html: Building ideas into reality through code, curiosity, and continuous experimentation.
  link_url: /projects

blog__settings:
  title: Recent Posts
  title_blog: Blog
  description_html: Thoughts, stories, and explorations in technology and life.
  link_url: /blog

testimonials__title: Testimonials
testimonials__description_html: "See what our satisfied customers have to say about their experience"

testimonials:
  - name: Sophia Ramirez
    position: Software Developer
    image: "images/client-1.jpg"
    blurb: This theme strikes the perfect balance between style and functionality, making it ideal for bloggers who want a professional and polished look.

  - name: Michael Thompson
    position: Digital Marketer
    image: "images/client-2.jpg"
    blurb: The attention to detail in this theme is outstanding—it’s intuitive, visually stunning, and works flawlessly across all platforms!

  - name: Daniel Carter
    position: Graphic Designer
    image: "images/client-3.jpg"
    blurb: The built-in features and smooth user experience make this theme stand out from the rest. It’s an absolute joy to work with!

  - name: Emily Johnson
    position: Freelance Writer
    image: "images/client-4.jpg"
    blurb: I love how well-optimized this theme is for speed and SEO; my blog has never performed better!

  - name: Jessica Bennett
    position: Content Creator
    image: "images/client-5.jpg"
    blurb: Elegant, modern, and highly customizable—this theme exceeded all my expectations for a Jekyll blog!

newsletter__settings:
  newsletter_title: Join my mailing list
  newsletter_description: Stay updated on raw stories!
  newsletter_identifier: https://buttondown.com/api/emails/embed-subscribe/swagatika.parthaa
  newsletter_button: Subscribe

contact_form__settings:
  form_title: Get in touch
  form_description: Have a question, an idea, or just want to say hello? I'd love to hear from you.
  form_button_text: Send now
  form_action_url: https://formspree.io/f/xkjorebn

#-------------------------------
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social_links:
  - { icon: "Twitter", link: "https://x.com/SwagatikaPartha" }
  - { icon: "Github", link: "https://github.com/parthaa-tech" }
  # - { icon: "Pinterest", link: "https://pinterest.com" }
  # - { icon: "Youtube", link: "https://youtube.com" }
